name: RPM Packaging

on:
  push:
    branches:
      - master

jobs:
  linux:
    name: RPM Packaging
    runs-on: ubuntu-20.04
    container: centos:centos7
    steps:
      - name: Install Dependencies
        run: |
          # CentOS 7's git version is too old for the checkout action so fetch from ius instead
          yum -y install https://repo.ius.io/ius-release-el7.rpm https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
          yum -y install git224 rpm-build rpm-sign rsync make gcc gcc-c++ gcc-gfortran wget unzip libquadmath libXt-devel libjpeg-devel zlib-devel freetype-devel atlas-devel lapack-devel openblas-devel openblas lapack python3-rpm-macros python3 python36-devel python3-setuptools

      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Clone Package Repository
        uses: actions/checkout@v2
        with:
          repository: warwick-one-metre/centos-packages
          token: ${{ secrets.DEPLOY_TOKEN }}
          path: centos-packages

      - name: Package Prereqs
        run:
          make prereq

      - name: Install Prereqs
        run: |
          echo "in directory" $(pwd)
          echo "dir contents" $(ls)
          rpm -i python3-numpy-*.rpm
          rpm -i python3-pybind11-*.rpm
          rpm -i python3-serpent-*.rpm

      - name: Package RPMs
        run:
          make general web

      - name: Push Packages
        env:
          RPM_SIGNING_KEY: ${{ secrets.RPM_SIGNING_KEY }}
        run: |
          centos-packages/sign-and-push-packages.sh *.rpm
