name: Rocky 9 Packaging

on:
  push:
    branches:
      - master

jobs:
  linux:
    strategy:
      matrix:
        os: [ ubuntu-22.04, ubuntu-22.04-arm ]
    name: RPM Packaging
    runs-on: ${{ matrix.os }}
    container: rockylinux:9
    steps:
      - name: Install Dependencies
        run: |
          cat /etc/redhat-release
          yum -y install epel-release
          /usr/bin/crb enable
          yum -y install gcc gcc-c++ git libXt-devel make python3-Cython python3-devel python3-extension-helpers python3-numpy python3-packaging python3-pip python3-pyparsing python3-pyyaml python3-rpm-macros rpm-build rpm-sign 

      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Package RPMs (x86_64 + noarch)
        if: ${{ !endsWith(matrix.os, 'arm') }}
        run: |
          make astropy-deps
          rpm -i python3-pyerfa-*.rpm
          make general web

      - name: Package RPMs (aarch64)
        if: ${{ endsWith(matrix.os, 'arm') }}
        run: |
          make astropy-deps
          rpm -i python3-pyerfa-*.rpm
          make aarch64

      - name: Clone Package Repository
        uses: actions/checkout@v4
        with:
          repository: rockit-astro/packages
          token: ${{ secrets.DEPLOY_TOKEN }}
          path: packages

      - name: Push Packages
        env:
          RPM_SIGNING_KEY: ${{ secrets.RPM_SIGNING_KEY }}
        run: |
          packages/sign-and-push-packages.sh *.rpm

